"""emit_c.py -- the compiled backend for WRL worlds: CompilePlanV1 view -> one C step function -> a shared object.

The interaction-calculus lowering (`forge/compiler.compile_step_v6`) turns a sealed world's plan into a term that is
reduced by ic_ref / ic32 / the checked Wasm host once per epoch. For the Golden demo world that term is 9.2 MB because
the spinner's Q16.8 multiplier is unrolled bit by bit; the reduction is 0.3 s on ic32 and 3-7 s on ic_ref. This module
lowers the SAME plan view -- the backend-neutral contract every codec and signature already project -- to a C function
over a flat int64 state vector, with the same field walk (`compiler.state_layout`), the same clock/wire/door/relay
laws, the same COMMIT-then-REACT order, and the same wide-MAC rotor law (`binlib.golden_rot_forge`, the shipping
`forge_motor_widemac_tz_sat_v1` policy, read from the same HAMILTON table).

It is admitted only by the fold: `fold.py` runs a world's scenario through this step and through the interaction
calculus and compares the decoded state and Forge's Film v0.7 epoch by epoch. Nothing here is trusted on its own.
Identity: `cbknd-` + sha256(SemanticArtifactID + profile + the emitted C source) -- a backend artifact id in the sense of
`wrl_canonical`, moving with the emitted code and never with the semantic id.

State vector layout (slots, int64): in `state_layout` order --
  counter onehot/binp -> 1 slot (the count)      counter once -> 2 slots (done, k)
  wire/door/relay     -> 2 slots (cur, nxt)      pose -> 4 lanes     fault -> 1     rotor -> 4 lanes
Control vector: per controlling spinner in ORB order (exactly `compiler.enc_config_bundle`'s walk) 5 slots
(set_flag, 4 lanes), then per orb 1 slot (reset_flag).
"""
import ctypes
import hashlib
import os
import subprocess
import tempfile

from compiler import pose_width, state_layout
from binlib import HAMILTON

PROFILE = "compiled.c.step.v1"
CACHE = os.environ.get("TRVM_COMPILED_CACHE") or os.path.expanduser("~/.cache/trvm-compiled")
MAX_LANE_WIDTH = 32   # products at 2w and a 4-term accumulator fit __int128 with room to spare; wider is refused


def slot_map(view):
    """[(kind, name, offset, nslots, spec)] in `state_layout` order, plus the total width."""
    out, off = [], 0
    for kind, name in state_layout(view):
        if kind == "counter":
            spec = view.counter_spec(name)
            n = 2 if spec[0] == "once" else 1
        elif kind in ("wire", "door", "relay"):
            spec, n = None, 2
        elif kind == "pose":
            spec, n = ("pose", pose_width(view, name)), 4
        elif kind == "fault":
            spec, n = None, 1
        elif kind == "rotor":
            spec, n = ("rotor", view.spinners[name][0]), 4
        else:
            raise AssertionError("emit_c: unhandled field kind %r" % kind)
        out.append((kind, name, off, n, spec))
        off += n
    return out, off


def control_layout(view):
    """(controlling spinners in orb order, orbs) -- the EpochControl walk of `enc_config_bundle`."""
    orbs = list(view.orbs)
    ctrl = [view.controller_of(o) for o in orbs if view.controller_of(o)]
    return ctrl, orbs


def emit_step_c(view):
    """The C source for one world's epoch step. Deterministic in the plan view."""
    fields, width = slot_map(view)
    off = {(k, n): o for k, n, o, _, _ in fields}
    spec = {n: s for k, n, _, _, s in fields if k == "counter"}
    ppl, wires, doors, relays = view.layout()
    orbs = list(view.orbs)
    ctrl, _ = control_layout(view)
    for s in view.spinners:
        w_ = view.spinners[s][0]
        if not (1 <= w_ <= MAX_LANE_WIDTH):
            raise ValueError("emit_c: lane width %d of spinner %s is outside 1..%d" % (w_, s, MAX_LANE_WIDTH))
    L = []
    emit = L.append
    emit("/* generated by TRVM compiled/emit_c.py -- profile %s -- do not edit */" % PROFILE)
    emit("#include <stdint.h>")
    emit("typedef int64_t i64; typedef __int128 i128;")
    emit("static inline i64 sx(i64 v, int w) { return v >= ((i64)1 << (w - 1)) ? v - ((i64)1 << w) : v; }")
    emit("/* HAMILTON rows from binlib: out[c] = sum sign * rotor[i] * pose[j] */")
    emit("static const int8_t HAM_SG[4][4] = {%s};" % ", ".join("{%s}" % ", ".join(str(sg) for sg, _, _ in row) for row in HAMILTON))
    emit("static const int8_t HAM_I[4][4] = {%s};" % ", ".join("{%s}" % ", ".join(str(i) for _, i, _ in row) for row in HAMILTON))
    emit("static const int8_t HAM_J[4][4] = {%s};" % ", ".join("{%s}" % ", ".join(str(j) for _, _, j in row) for row in HAMILTON))
    emit("/* golden_mac: full-precision products, ONE toward-zero shift, ONE saturation; returns the overflow flag */")
    emit("static int mac_row(int w, int n, int c, const i64 *rotor, const i64 *pose, i64 *out) {")
    emit("  i128 acc = 0;")
    emit("  for (int k = 0; k < 4; k++) acc += (i128)HAM_SG[c][k] * ((i128)sx(rotor[HAM_I[c][k]], w) * (i128)sx(pose[HAM_J[c][k]], w));")
    emit("  i128 q = acc >= 0 ? (acc >> n) : -((-acc) >> n);")
    emit("  i128 lo = -((i128)1 << (w - 1)), hi = ((i128)1 << (w - 1)) - 1;")
    emit("  int ov = !(lo <= q && q <= hi);")
    emit("  i128 s = q < lo ? lo : (q > hi ? hi : q);")
    emit("  *out = (i64)(s & (((i128)1 << w) - 1));")
    emit("  return ov;")
    emit("}")
    emit("/* golden_rot_forge: (4 lanes, fault) */")
    emit("static int rot_forge(int w, int n, const i64 *rotor, const i64 *pose, i64 *out) {")
    emit("  int fault = 0;")
    emit("  for (int c = 0; c < 4; c++) fault |= mac_row(w, n, c, rotor, pose, &out[c]);")
    emit("  return fault;")
    emit("}")
    emit("int state_width(void) { return %d; }" % width)
    emit("int control_width(void) { return %d; }" % (5 * len(ctrl) + len(orbs)))
    emit("void step_v6(const i64 *st, const i64 *ctl, i64 *out) {")
    # ---- clocks: fire predicate and next count
    for r in ppl:
        sp = spec[r]
        o = off[("counter", r)]
        if sp[0] == "onehot":
            _, p, ph = sp
            emit("  /* pulser %s: one-hot period %d phase %d */" % (r, p, ph))
            emit("  const i64 c_%d = st[%d];" % (o, o))
            emit("  const int fire_%d = (c_%d == %d); /* one-hot */" % (o, o, ph))
            emit("  out[%d] = (c_%d + 1) %% %d;" % (o, o, p))
        elif sp[0] == "binp":
            _, p, ph, w_ = sp
            emit("  /* pulser %s: binary period %d phase %d width %d */" % (r, p, ph, w_))
            emit("  const i64 c_%d = st[%d];" % (o, o))
            emit("  const int fire_%d = (c_%d == %d); /* binary */" % (o, o, ph))
            emit("  { const i64 sum = (c_%d + 1) & %d; out[%d] = (sum == %d) ? 0 : sum; }" % (o, (1 << w_) - 1, o, p))
        else:
            _, e, w_ = sp
            emit("  /* pulser %s: once at %d width %d (done, k) */" % (r, e, w_))
            emit("  const i64 done_%d = st[%d], k_%d = st[%d];" % (o, o, o, o + 1))
            emit("  const int fire_%d = (!done_%d && k_%d == %d);" % (o, o, o, e))
            emit("  out[%d] = done_%d || fire_%d; out[%d] = (k_%d + 1) & %d;" % (o, o, o, o + 1, o, (1 << w_) - 1))
    # ---- hot signals: a pulser's fire, a relay's NEXT output
    for r in ppl:
        if view.out_wires(r):
            emit("  const int hot_%s = fire_%d;" % (_cid(r), off[("counter", r)]))
    for r in relays:
        if view.out_wires(r):
            emit("  const int hot_%s = (int)st[%d]; /* relay %s nxt */" % (_cid(r), off[("relay", r)] + 1, r))

    def merge_in(role):
        ins = view.in_wires(role)
        if not ins:
            return "0"
        return " | ".join("(int)st[%d]" % (off[("wire", wr)] + 1) for wr in ins)

    # ---- wires: (cur', nxt') = (nxt, source hot)
    src_of = {}
    for role in list(ppl) + list(relays):
        for wr in view.out_wires(role):
            src_of[wr] = role
    for wr in wires:
        o = off[("wire", wr)]
        emit("  out[%d] = st[%d]; out[%d] = hot_%s; /* wire %s */" % (o, o + 1, o + 1, _cid(src_of[wr]), wr))
    for d in doors:
        o = off[("door", d)]
        emit("  out[%d] = st[%d]; out[%d] = %s; /* door %s */" % (o, o + 1, o + 1, merge_in(d), d))
    for r in relays:
        o = off[("relay", r)]
        emit("  out[%d] = st[%d]; out[%d] = %s; /* relay %s */" % (o, o + 1, o + 1, merge_in(r), r))
    # ---- orbs: COMMIT the fault reset and the rotor config, then REACT
    for i, ob in enumerate(orbs):
        po, fo = off[("pose", ob)], off[("fault", ob)]
        reset_slot = 5 * len(ctrl) + i
        emit("  { /* orb %s */" % ob)
        emit("    const int fbase = ctl[%d] ? 0 : (int)st[%d]; /* COMMIT fault reset */" % (reset_slot, fo))
        s = view.controller_of(ob)
        if not s:
            emit("    out[%d] = st[%d]; out[%d] = st[%d]; out[%d] = st[%d]; out[%d] = st[%d]; out[%d] = fbase; /* no controller */"
                 % (po, po, po + 1, po + 1, po + 2, po + 2, po + 3, po + 3, fo))
            emit("  }")
            continue
        w_, n_, _ = view.spinners[s]
        ro = off[("rotor", s)]
        ci = 5 * ctrl.index(s)
        emit("    const i64 *old_rotor = &st[%d]; const i64 *old_pose = &st[%d];" % (ro, po))
        emit("    i64 eff[4]; /* COMMIT rotor config: SetRotor replaces, NoChange keeps */")
        emit("    for (int l = 0; l < 4; l++) eff[l] = ctl[%d] ? ctl[%d + l] : old_rotor[l];" % (ci, ci + 1))
        emit("    for (int l = 0; l < 4; l++) out[%d + l] = eff[l];" % ro)
        emit("    const int sel = %s; /* spinner %s merged input */" % (merge_in(s), s))
        emit("    if (sel) { /* REACT over the committed rotor */")
        emit("      const int ov = rot_forge(%d, %d, eff, old_pose, &out[%d]);" % (w_, n_, po))
        emit("      out[%d] = fbase | ov; /* sticky fault */" % fo)
        emit("    } else {")
        emit("      for (int l = 0; l < 4; l++) out[%d + l] = old_pose[l];" % po)
        emit("      out[%d] = fbase;" % fo)
        emit("    }")
        emit("  }")
    emit("}")
    return "\n".join(L) + "\n"


def _cid(role):
    return "".join(ch if ch.isalnum() else "_%02x" % ord(ch) for ch in role)


def backend_id(sem_id, source):
    return "cbknd-" + hashlib.sha256((sem_id + "\n" + PROFILE + "\n" + source).encode()).hexdigest()


def build(source, cc="gcc"):
    """Content-addressed build: the .so is keyed by the sha256 of the source; temp compile then atomic rename."""
    os.makedirs(CACHE, exist_ok=True)
    key = hashlib.sha256(source.encode()).hexdigest()
    so = os.path.join(CACHE, key + ".so")
    if os.path.exists(so):
        return so, key, False
    with tempfile.TemporaryDirectory(dir=CACHE) as td:
        csrc = os.path.join(td, "step.c")
        with open(csrc, "w") as f:
            f.write(source)
        tmp_so = os.path.join(td, "step.so")
        subprocess.run([cc, "-O2", "-shared", "-fPIC", "-o", tmp_so, csrc], check=True, capture_output=True)
        os.replace(tmp_so, so)
    return so, key, True


class CompiledStep:
    """One world's compiled epoch step. `step(st, cfg_map, resets)` takes and returns the SAME state dict shape
    that `compiler.enc_state_v6` consumes and `compiler.dec_state_v6` produces."""

    def __init__(self, view, sem_id="", cc="gcc"):
        self.view = view
        self.fields, self.width = slot_map(view)
        self.ctrl, self.orbs = control_layout(view)
        self.source = emit_step_c(view)
        self.backend_id = backend_id(sem_id, self.source)
        self.so_path, self.source_sha256, self.built_now = build(self.source, cc)
        self._lib = ctypes.CDLL(self.so_path)
        assert self._lib.state_width() == self.width
        assert self._lib.control_width() == 5 * len(self.ctrl) + len(self.orbs)
        self._Arr = ctypes.c_int64 * self.width
        self._Ctl = ctypes.c_int64 * (5 * len(self.ctrl) + len(self.orbs))
        self._lib.step_v6.argtypes = [ctypes.POINTER(ctypes.c_int64)] * 3
        self._lib.step_v6.restype = None

    def encode(self, st):
        a = self._Arr()
        for kind, name, o, n, spec in self.fields:
            if kind == "counter":
                if spec[0] == "once":
                    done, k = st["c_" + name]
                    a[o], a[o + 1] = int(done), int(k)
                else:
                    a[o] = int(st["c_" + name])
            elif kind in ("wire", "door", "relay"):
                x, y = st[name]
                a[o], a[o + 1] = int(bool(x)), int(bool(y))
            elif kind == "pose":
                for l, v in enumerate(st["pose_" + name]):
                    a[o + l] = int(v)
            elif kind == "fault":
                a[o] = int(st.get("fault_" + name, 0))
            elif kind == "rotor":
                for l, v in enumerate(st["rotor_" + name]):
                    a[o + l] = int(v)
        return a

    def decode(self, a):
        st = {}
        for kind, name, o, n, spec in self.fields:
            if kind == "counter":
                st["c_" + name] = (int(a[o]), int(a[o + 1])) if spec[0] == "once" else int(a[o])
            elif kind in ("wire", "door", "relay"):
                st[name] = (bool(a[o]), bool(a[o + 1]))
            elif kind == "pose":
                st["pose_" + name] = tuple(int(a[o + l]) for l in range(4))
            elif kind == "fault":
                st["fault_" + name] = int(a[o])
            elif kind == "rotor":
                st["rotor_" + name] = tuple(int(a[o + l]) for l in range(4))
        return st

    def control(self, cfg_map, resets):
        c = self._Ctl()
        for i, s in enumerate(self.ctrl):
            cfg = cfg_map.get(s)
            if cfg is not None:
                c[5 * i] = 1
                for l in range(4):
                    c[5 * i + 1 + l] = int(cfg[l])
        for i, o in enumerate(self.orbs):
            c[5 * len(self.ctrl) + i] = 1 if (resets or {}).get(o) else 0
        return c

    def step(self, st, cfg_map, resets=None):
        a, c, out = self.encode(st), self.control(cfg_map, resets), self._Arr()
        self._lib.step_v6(a, c, out)
        return self.decode(out)
