"""emit_c2.py -- the C backend, second representation: the signal state bit-packed into 64-bit words.

`emit_c.py` (v1) gives every wire, door and relay two int64 slots and assigns them one by one; on chain120 that is 485 slots
copied per epoch, and the Bend backend's packed representation (`emit_bend2.py`) ran under it (0.032 vs 0.071 us, 2026-09-18).
The gap was the representation, not the language, and the C side had had no performance pass at all. This emitter keeps the
LAWS of v1 -- the clock/wire/door/relay laws of `compile_step_v6`, COMMIT-then-REACT per orb, the wide-MAC of
`binlib.golden_rot_forge` in i128 with one toward-zero shift and one saturation -- and changes the representation exactly
as the Bend v2 did, with 64-bit words: positions are assigned along each chain (`emit_bend2.signal_layout`) so the two wire
laws are one masked shift per (source word, target word, displacement) run and `cur' = nxt` a word copy. The MAC is v1's.
Pointers are `restrict`; the compiler flags are part of the identity (`TRVM_CFLAGS`, default `-O2`), because a build's
flags change the machine code that is being admitted.

The vector on the wire is the PACKED one (counters, CUR words, NXT words, poses, faults, rotors); the battery speaks v1's
slot vector, packed and unpacked on the Python side by the same layout function the emitter uses (word = 64). Identity:
`cbknd2-` + sha256(SemanticArtifactID + `compiled.c.step.v2` + flags + the emitted source).
"""
import ctypes
import hashlib
import os
import subprocess
import tempfile

from binlib import HAMILTON
from emit_c import slot_map, control_layout, CompiledStep, MAX_LANE_WIDTH, CACHE
from emit_bend2 import packed_layout, pack_vector, unpack_vector

PROFILE = "compiled.c.step.v2"
WORD = 64
CFLAGS = os.environ.get("TRVM_CFLAGS", "-O2").split()


def emit_step_c2(view):
    fields, width, pos, nwords, packed, _w = packed_layout(view, WORD)
    spec = {n: s for k, n, _, _, s in fields if k == "counter"}
    ppl, wires, doors, relays = view.layout()
    orbs = list(view.orbs)
    ctrl, _ = control_layout(view)
    for s in view.spinners:
        w_ = view.spinners[s][0]
        if not (1 <= w_ <= MAX_LANE_WIDTH):
            raise ValueError("emit_c2: lane width %d of spinner %s is outside 1..%d" % (w_, s, MAX_LANE_WIDTH))
    idx, i = {}, 0
    for kind, name, o, n, sp in packed:
        idx[(kind, name)] = i
        i += n
    pw = i
    cw = 5 * len(ctrl) + len(orbs)
    L = []
    emit = L.append
    emit("/* generated by TRVM compiled/emit_c2.py -- profile %s -- do not edit */" % PROFILE)
    emit("#include <stdint.h>")
    emit("typedef int64_t i64; typedef uint64_t u64; typedef __int128 i128;")
    emit("static inline i128 sx(i64 v, int w) { i128 x = v; return x >= ((i128)1 << (w - 1)) ? x - ((i128)1 << w) : x; }")
    emit("static const int8_t HAM_SG[4][4] = {%s};" % ", ".join("{%s}" % ", ".join(str(sg) for sg, _, _ in row) for row in HAMILTON))
    emit("static const int8_t HAM_I[4][4] = {%s};" % ", ".join("{%s}" % ", ".join(str(i) for _, i, _ in row) for row in HAMILTON))
    emit("static const int8_t HAM_J[4][4] = {%s};" % ", ".join("{%s}" % ", ".join(str(j) for _, _, j in row) for row in HAMILTON))
    emit("static inline int mac_row(int w, int n, int c, const i64 *rotor, const i64 *pose, i64 *out) {")
    emit("  i128 acc = 0;")
    emit("  for (int k = 0; k < 4; k++) acc += (i128)HAM_SG[c][k] * (sx(rotor[HAM_I[c][k]], w) * sx(pose[HAM_J[c][k]], w)); /* i128 products */")
    emit("  i128 q = acc >= 0 ? (acc >> n) : -((-acc) >> n);")
    emit("  i128 lo = -((i128)1 << (w - 1)), hi = ((i128)1 << (w - 1)) - 1;")
    emit("  int ov = !(lo <= q && q <= hi);")
    emit("  i128 s = q < lo ? lo : (q > hi ? hi : q);")
    emit("  *out = (i64)(s & (((i128)1 << w) - 1));")
    emit("  return ov;")
    emit("}")
    emit("static inline int rot_forge(int w, int n, const i64 *rotor, const i64 *pose, i64 *out) {")
    emit("  int fault = 0;")
    emit("  for (int c = 0; c < 4; c++) fault |= mac_row(w, n, c, rotor, pose, &out[c]);")
    emit("  return fault;")
    emit("}")
    emit("int state_width(void) { return %d; }" % pw)
    emit("int control_width(void) { return %d; }" % cw)
    emit("void step_v6(const i64 *restrict st, const i64 *restrict ctl, i64 *restrict out) {")
    cur0, nxt0 = idx[("cur", None)], idx[("nxt", None)]
    for k in range(nwords):
        emit("  const u64 n%d = (u64)st[%d]; /* NXT word %d */" % (k, nxt0 + k, k))
    fire_u = {}
    for r in ppl:
        sp, o = spec[r], idx[("counter", r)]
        if sp[0] == "onehot":
            _, p, ph = sp
            emit("  /* pulser %s: one-hot period %d phase %d */" % (r, p, ph))
            emit("  const int fire_%d = (st[%d] == %d); /* one-hot */" % (o, o, ph))
            emit("  out[%d] = (st[%d] + 1) %% %d;" % (o, o, p))
        elif sp[0] == "binp":
            _, p, ph, w_ = sp
            emit("  /* pulser %s: binary period %d phase %d width %d */" % (r, p, ph, w_))
            emit("  const int fire_%d = (st[%d] == %d); /* binary */" % (o, o, ph))
            emit("  { const i64 sum = (st[%d] + 1) & %d; out[%d] = (sum == %d) ? 0 : sum; }" % (o, (1 << w_) - 1, o, p))
        else:
            _, e, w_ = sp
            emit("  /* pulser %s: once at %d width %d (done, k) */" % (r, e, w_))
            emit("  const int fire_%d = (!st[%d] && st[%d] == %d);" % (o, o, o + 1, e))
            emit("  out[%d] = st[%d] || fire_%d; out[%d] = (st[%d] + 1) & %d;" % (o, o, o, o + 1, o + 1, (1 << w_) - 1))
        if view.out_wires(r):
            fire_u[r] = "fire_%d" % o
    # ---- signal words
    edges, fires, src_of = [], [], {}
    for role in list(ppl) + list(relays):
        for wr in view.out_wires(role):
            src_of[wr] = role
    for wr in wires:
        p, s = pos[wr], src_of[wr]
        if s in ppl:
            fires.append((p // WORD, p % WORD, fire_u[s]))
        else:
            q = pos[s]
            edges.append((q // WORD, q % WORD, p // WORD, p % WORD))
    for d in list(doors) + list(relays):
        for wr in view.in_wires(d):
            q, p = pos[wr], pos[d]
            edges.append((q // WORD, q % WORD, p // WORD, p % WORD))
    runs = {}
    for sw, sb, dw, db in edges:
        runs[(sw, dw, db - sb)] = runs.get((sw, dw, db - sb), 0) | (1 << sb)
    for k in range(nwords):
        parts = []
        for (sw, dw, disp), mask in sorted(runs.items()):
            if dw != k:
                continue
            parts.append("((n%d & 0x%xULL) %s %d)" % (sw, mask, "<<" if disp >= 0 else ">>", abs(disp)))
        for dw, db, fexpr in fires:
            if dw == k:
                parts.append("((u64)%s << %d)" % (fexpr, db))
        emit("  out[%d] = st[%d]; /* CUR word %d <- NXT */" % (cur0 + k, nxt0 + k, k))
        emit("  out[%d] = (i64)(%s); /* NXT word %d */" % (nxt0 + k, " | ".join(parts) if parts else "0", k))
    # ---- orbs
    for i_, ob in enumerate(orbs):
        po, fo = idx[("pose", ob)], idx[("fault", ob)]
        reset_slot = 5 * len(ctrl) + i_
        emit("  { /* orb %s */" % ob)
        emit("    const int fbase = ctl[%d] ? 0 : (int)st[%d]; /* COMMIT fault reset */" % (reset_slot, fo))
        s = view.controller_of(ob)
        if not s:
            emit("    out[%d] = st[%d]; out[%d] = st[%d]; out[%d] = st[%d]; out[%d] = st[%d]; out[%d] = fbase; /* no controller */"
                 % (po, po, po + 1, po + 1, po + 2, po + 2, po + 3, po + 3, fo))
            emit("  }")
            continue
        w_, n_, _ = view.spinners[s]
        ro, ci = idx[("rotor", s)], 5 * ctrl.index(s)
        emit("    const i64 *old_rotor = &st[%d]; const i64 *old_pose = &st[%d];" % (ro, po))
        emit("    i64 eff[4]; /* COMMIT rotor config: SetRotor replaces, NoChange keeps */")
        emit("    for (int l = 0; l < 4; l++) eff[l] = ctl[%d] ? ctl[%d + l] : old_rotor[l];" % (ci, ci + 1))
        emit("    for (int l = 0; l < 4; l++) out[%d + l] = eff[l];" % ro)
        ins = view.in_wires(s)
        if ins:
            p = pos[ins[0]]
            emit("    const int sel = (int)((n%d >> %d) & 1); /* spinner %s input fires */" % (p // WORD, p % WORD, s))
        else:
            emit("    const int sel = 0;")
        emit("    if (sel) { /* REACT over the committed rotor */")
        emit("      const int ov = rot_forge(%d, %d, eff, old_pose, &out[%d]);" % (w_, n_, po))
        emit("      out[%d] = fbase | ov; /* sticky fault */" % fo)
        emit("    } else {")
        emit("      for (int l = 0; l < 4; l++) out[%d + l] = old_pose[l];" % po)
        emit("      out[%d] = fbase;" % fo)
        emit("    }")
        emit("  }")
    emit("}")
    return "\n".join(L) + "\n", pw


def backend_id(sem_id, source, flags):
    return "cbknd2-" + hashlib.sha256((sem_id + "\n" + PROFILE + "\n" + " ".join(flags) + "\n" + source).encode()).hexdigest()


def build(source, flags, cc="gcc"):
    os.makedirs(CACHE, exist_ok=True)
    key = hashlib.sha256((" ".join(flags) + "\n" + source).encode()).hexdigest()
    so = os.path.join(CACHE, key + ".so")
    if os.path.exists(so):
        return so, key, False
    with tempfile.TemporaryDirectory(dir=CACHE) as td:
        csrc = os.path.join(td, "step.c")
        with open(csrc, "w") as f:
            f.write(source)
        tmp_so = os.path.join(td, "step.so")
        subprocess.run([cc] + flags + ["-shared", "-fPIC", "-o", tmp_so, csrc], check=True, capture_output=True)
        os.replace(tmp_so, so)
    return so, key, True


class CompiledStep2(CompiledStep):
    """v2: the packed vector in the .so, v1's slot vector to the battery."""

    def __init__(self, view, sem_id="", flags=None):
        self.view = view
        self.flags = list(flags or CFLAGS)
        self.fields, self.width = slot_map(view)
        self.ctrl, self.orbs = control_layout(view)
        self.layout = packed_layout(view, WORD)
        self.source, self.packed_width = emit_step_c2(view)
        self.backend_id = backend_id(sem_id, self.source, self.flags)
        self.so_path, self.source_sha256, self.built_now = build(self.source, self.flags)
        self._lib = ctypes.CDLL(self.so_path)
        assert self._lib.state_width() == self.packed_width
        assert self._lib.control_width() == 5 * len(self.ctrl) + len(self.orbs)
        self._Arr = ctypes.c_int64 * self.width
        self._Packed = ctypes.c_int64 * self.packed_width
        self._Ctl = ctypes.c_int64 * (5 * len(self.ctrl) + len(self.orbs))
        self._lib.step_v6.argtypes = [ctypes.POINTER(ctypes.c_int64)] * 3
        self._lib.step_v6.restype = None

    def pack(self, a):
        return pack_vector(self.view, list(a), self.layout)

    def unpack(self, vals):
        return unpack_vector(self.view, list(vals), self.layout)

    def step(self, st, cfg_map, resets=None):
        a, c = self.encode(st), self.control(cfg_map, resets)
        pin, pout = self._Packed(*self.pack(a)), self._Packed()
        self._lib.step_v6(pin, c, pout)
        out = self._Arr(*self.unpack(pout))
        return self.decode(out)
