"""emit_c.py -- the compiled backend for WRL worlds: CompilePlanV1 view -> one C step function -> a shared object.

The interaction-calculus lowering (`forge/compiler.compile_step_v6`) turns a sealed world's plan into a term that is
reduced by ic_ref / ic32 / the checked Wasm host once per epoch. For the Golden demo world that term is 9.2 MB because
the spinner's Q16.8 multiplier is unrolled bit by bit; the reduction is 0.3 s on ic32 and 3-7 s on ic_ref. This module
lowers the SAME plan view -- the backend-neutral contract every codec and signature already project -- to a C function
over a flat int64 state vector, with the same field walk (`compiler.state_layout`), the same clock/wire/door/relay
laws, the same COMMIT-then-REACT order, and the same wide-MAC rotor law (`binlib.golden_rot_forge`, the shipping
`forge_motor_widemac_tz_sat_v1` policy, read from the same HAMILTON table).

It is admitted only by the fold: `fold.py` runs a world's scenario through this step and through the interaction
calculus and compares the decoded state and Forge's Film v0.7 epoch by epoch. Nothing here is trusted on its own.
Identity: `cbknd-` + sha256(SemanticArtifactID + profile + the emitted C source) -- a backend artifact id in the sense of
`wrl_canonical`, moving with the emitted code and never with the semantic id.

State vector layout (slots, int64): in `state_layout` order --
  counter onehot/binp -> 1 slot (the count)      counter once -> 2 slots (done, k)
  wire/door/relay     -> 2 slots (cur, nxt)      pose -> 4 lanes     fault -> 1     rotor -> 4 lanes
Control vector: per controlling spinner in ORB order (exactly `compiler.enc_config_bundle`'s walk) 5 slots
(set_flag, 4 lanes), then per orb 1 slot (reset_flag).
"""
import ctypes
import hashlib
import os
import re
import subprocess
import tempfile

from compiler import pose_width, state_layout
from binlib import HAMILTON
import laws as LAW

PROFILE = "compiled.c.step.v1"
CACHE = os.environ.get("TRVM_COMPILED_CACHE") or os.path.expanduser("~/.cache/trvm-compiled")
MAX_LANE_WIDTH = 63   # lanes live in int64 slots and the 4-term accumulator |acc| <= 2^(2w) must fit __int128:
                      # 2^126 < 2^127 at w=63; w=64 would need a 65-bit lane. Widths above 32 were refused until
                      # 2026-09-18 (the battery admits w=33 since then; see README section 2b).


def slot_map(view):
    """[(kind, name, offset, nslots, spec)] in `state_layout` order, plus the total width."""
    out, off = [], 0
    for kind, name in state_layout(view):
        if kind == "counter":
            spec = view.counter_spec(name)
            n = 2 if spec[0] == "once" else 1
        elif kind in ("wire", "door", "relay"):
            spec, n = None, 2
        elif kind == "pose":
            spec, n = ("pose", pose_width(view, name)), 4
        elif kind == "fault":
            spec, n = None, 1
        elif kind == "rotor":
            spec, n = ("rotor", view.spinners[name][0]), 4
        else:
            raise AssertionError("emit_c: unhandled field kind %r" % kind)
        out.append((kind, name, off, n, spec))
        off += n
    return out, off


def control_layout(view):
    """(controlling spinners in orb order, orbs) -- the EpochControl walk of `enc_config_bundle`."""
    orbs = list(view.orbs)
    ctrl = [view.controller_of(o) for o in orbs if view.controller_of(o)]
    return ctrl, orbs


def emit_step_c(view):
    """The C source for one world's epoch step. Deterministic in the plan view."""
    fields, width = slot_map(view)
    off = {(k, n): o for k, n, o, _, _ in fields}
    spec = {n: s for k, n, _, _, s in fields if k == "counter"}
    ppl, wires, doors, relays = view.layout()
    orbs = list(view.orbs)
    ctrl, _ = control_layout(view)
    for s in view.spinners:
        w_ = view.spinners[s][0]
        if not (1 <= w_ <= MAX_LANE_WIDTH):
            raise ValueError("emit_c: lane width %d of spinner %s is outside 1..%d" % (w_, s, MAX_LANE_WIDTH))
    L = []
    emit = L.append
    emit("/* generated by TRVM compiled/emit_c.py -- profile %s -- do not edit */" % PROFILE)
    emit("#include <stdint.h>")
    emit("typedef int64_t i64; typedef __int128 i128;")
    for line in LAW.render("c", "mac"):
        emit(line)
    emit("int state_width(void) { return %d; }" % width)
    emit("int control_width(void) { return %d; }" % (5 * len(ctrl) + len(orbs)))
    emit("void step_v6(const i64 *st, const i64 *ctl, i64 *out) {")
    # ---- clocks: fire predicate and next count (laws.py: clock-onehot / clock-binary / clock-once)
    for r in ppl:
        sp = spec[r]
        o = off[("counter", r)]
        if sp[0] == "onehot":
            _, p, ph = sp
            L += LAW.render("c", "clock-onehot", o=o, p=p, ph=ph, r=r)
        elif sp[0] == "binp":
            _, p, ph, w_ = sp
            L += LAW.render("c", "clock-binary", o=o, p=p, ph=ph, w=w_, r=r)
        else:
            _, e, w_ = sp
            L += LAW.render("c", "clock-once", o=o, e=e, w=w_, r=r)
    # ---- hot signals: a pulser's fire, a relay's NEXT output
    for r in ppl:
        if view.out_wires(r):
            L += LAW.render("c", "hot-pulser", cid=_cid(r), o=off[("counter", r)])
    for r in relays:
        if view.out_wires(r):
            L += LAW.render("c", "hot-relay", cid=_cid(r), o=off[("relay", r)], r=r)

    def merge_in(role):
        ins = view.in_wires(role)
        if not ins:
            return "0"
        return " | ".join("(int)st[%d]" % (off[("wire", wr)] + 1) for wr in ins)

    # ---- wires: (cur', nxt') = (nxt, source hot); doors and relays take their inputs' nxt
    src_of = {}
    for role in list(ppl) + list(relays):
        for wr in view.out_wires(role):
            src_of[wr] = role
    for wr in wires:
        L += LAW.render("c", "wire", o=off[("wire", wr)], cid=_cid(src_of[wr]), wr=wr)
    for d in doors:
        L += LAW.render("c", "sink", o=off[("door", d)], merged=merge_in(d), kind="door", name=d)
    for r in relays:
        L += LAW.render("c", "sink", o=off[("relay", r)], merged=merge_in(r), kind="relay", name=r)
    # ---- orbs: COMMIT the fault reset and the rotor config, then REACT
    for i, ob in enumerate(orbs):
        po, fo = off[("pose", ob)], off[("fault", ob)]
        reset_slot = 5 * len(ctrl) + i
        emit("  { /* orb %s */" % ob)
        L += LAW.render("c", "commit-fault-reset", reset_slot=reset_slot, fo=fo)
        s = view.controller_of(ob)
        if not s:
            L += LAW.render("c", "orb-uncontrolled", po=po, fo=fo)
            emit("  }")
            continue
        w_, n_, _ = view.spinners[s]
        ro = off[("rotor", s)]
        ci = 5 * ctrl.index(s)
        L += LAW.render("c", "commit-rotor", ro=ro, po=po, ci=ci)
        L += LAW.render("c", "react", po=po, fo=fo, w=w_, n=n_, s=s, sel=merge_in(s))
        emit("  }")
    emit("}")
    return "\n".join(L) + "\n"


def _cid(role):
    return "".join(ch if ch.isalnum() else "_%02x" % ord(ch) for ch in role)



# -------------------------------------------------------------------------------------------- the toolchain's identity
_TOOLCHAIN = {}


def toolchain_identity(flags, cc="gcc"):
    """What the COMPILER contributes to a built step's identity (`FLAGS_POLICY.md` choice 5, ruled 2026-09-19).

    A flag string is not machine code. `-march=native` hashes as the six letters "native" while the compiler
    resolves it to the build machine's CPU (`znver5` on this laptop), so two hosts can share a `cbknd2-` id and
    disagree in every instruction; and a gcc upgrade leaves the id untouched entirely. Three lines, every one of
    them read back FROM the compiler with the flags applied, never guessed:

        cc <the --version first line>
        target <-dumpmachine>
        march=<resolved> mtune=<resolved>       # from `-Q --help=target`, which is what resolves `native`

    Deterministic for a fixed (cc, flags) on a fixed toolchain; memoised, because `-Q --help=target` is a
    subprocess and the battery builds one step per world. A compiler that does not answer `-Q --help=target`
    (clang does not) records the two lines it does answer and `march=<unresolved>`: that is strictly more than
    the flag string alone, and it is said here rather than hidden, because an identity that silently degrades is
    the defect this function exists to close.
    """
    key = (cc, tuple(flags))
    if key in _TOOLCHAIN:
        return _TOOLCHAIN[key]

    def run(args):
        try:
            p = subprocess.run([cc] + args, capture_output=True, text=True)
            return (p.stdout or "") + (p.stderr or "")
        except OSError as e:
            return "<%s: %s>" % (cc, e)

    version = (run(["--version"]).splitlines() or ["<no --version>"])[0].strip()
    target = (run(["-dumpmachine"]).splitlines() or ["<no -dumpmachine>"])[0].strip()
    resolved = {}
    for line in run(list(flags) + ["-Q", "--help=target"]).splitlines():
        m = re.match(r"\s+-m(arch|tune)=\s+(\S+)\s*$", line)
        if m:
            resolved.setdefault(m.group(1), m.group(2))
    text = "cc %s\ntarget %s\nmarch=%s mtune=%s\n" % (
        version, target, resolved.get("arch", "<unresolved>"), resolved.get("tune", "<unresolved>"))
    _TOOLCHAIN[key] = text
    return text


def toolchain_dir(flags, cc="gcc"):
    """The object cache, namespaced by the toolchain that built it.

    The cache key stays sha256(source) for v1 and sha256(flags + source) for v2 -- both are reported as
    `source_sha256` and neither moves -- but the OBJECT for one key under two compilers is two objects. Without
    this namespace a gcc upgrade serves the old `.so` to the new identity, which would make choice 5's identity
    change worse than no change at all: a new id on old bytes.
    """
    d = os.path.join(CACHE, "tc-" + hashlib.sha256(toolchain_identity(flags, cc).encode()).hexdigest()[:16])
    os.makedirs(d, exist_ok=True)
    return d


def backend_id(sem_id, source):
    return "cbknd-" + hashlib.sha256((sem_id + "\n" + PROFILE + "\n" + source).encode()).hexdigest()


def build(source, cc="gcc"):
    """Content-addressed build: the .so is keyed by the sha256 of the source; temp compile then atomic rename."""
    key = hashlib.sha256(source.encode()).hexdigest()
    so = os.path.join(toolchain_dir(["-O2"], cc), key + ".so")
    if os.path.exists(so):
        return so, key, False
    with tempfile.TemporaryDirectory(dir=os.path.dirname(so)) as td:
        csrc = os.path.join(td, "step.c")
        with open(csrc, "w") as f:
            f.write(source)
        tmp_so = os.path.join(td, "step.so")
        subprocess.run([cc, "-O2", "-shared", "-fPIC", "-o", tmp_so, csrc], check=True, capture_output=True)
        os.replace(tmp_so, so)
    return so, key, True


class CompiledStep:
    """One world's compiled epoch step. `step(st, cfg_map, resets)` takes and returns the SAME state dict shape
    that `compiler.enc_state_v6` consumes and `compiler.dec_state_v6` produces."""

    def __init__(self, view, sem_id="", cc="gcc"):
        self.view = view
        self.fields, self.width = slot_map(view)
        self.ctrl, self.orbs = control_layout(view)
        self.source = emit_step_c(view)
        self.backend_id = backend_id(sem_id, self.source)
        self.so_path, self.source_sha256, self.built_now = build(self.source, cc)
        self._lib = ctypes.CDLL(self.so_path)
        assert self._lib.state_width() == self.width
        assert self._lib.control_width() == 5 * len(self.ctrl) + len(self.orbs)
        self._Arr = ctypes.c_int64 * self.width
        self._Ctl = ctypes.c_int64 * (5 * len(self.ctrl) + len(self.orbs))
        self._lib.step_v6.argtypes = [ctypes.POINTER(ctypes.c_int64)] * 3
        self._lib.step_v6.restype = None

    def encode(self, st):
        a = self._Arr()
        for kind, name, o, n, spec in self.fields:
            if kind == "counter":
                if spec[0] == "once":
                    done, k = st["c_" + name]
                    a[o], a[o + 1] = int(done), int(k)
                else:
                    a[o] = int(st["c_" + name])
            elif kind in ("wire", "door", "relay"):
                x, y = st[name]
                a[o], a[o + 1] = int(bool(x)), int(bool(y))
            elif kind == "pose":
                for l, v in enumerate(st["pose_" + name]):
                    a[o + l] = int(v)
            elif kind == "fault":
                a[o] = int(st.get("fault_" + name, 0))
            elif kind == "rotor":
                for l, v in enumerate(st["rotor_" + name]):
                    a[o + l] = int(v)
        return a

    def decode(self, a):
        st = {}
        for kind, name, o, n, spec in self.fields:
            if kind == "counter":
                st["c_" + name] = (int(a[o]), int(a[o + 1])) if spec[0] == "once" else int(a[o])
            elif kind in ("wire", "door", "relay"):
                st[name] = (bool(a[o]), bool(a[o + 1]))
            elif kind == "pose":
                st["pose_" + name] = tuple(int(a[o + l]) for l in range(4))
            elif kind == "fault":
                st["fault_" + name] = int(a[o])
            elif kind == "rotor":
                st["rotor_" + name] = tuple(int(a[o + l]) for l in range(4))
        return st

    def control(self, cfg_map, resets):
        c = self._Ctl()
        for i, s in enumerate(self.ctrl):
            cfg = cfg_map.get(s)
            if cfg is not None:
                c[5 * i] = 1
                for l in range(4):
                    c[5 * i + 1 + l] = int(cfg[l])
        for i, o in enumerate(self.orbs):
            c[5 * len(self.ctrl) + i] = 1 if (resets or {}).get(o) else 0
        return c

    def step_raw(self, a, c):
        """The C call alone: slot vector in, slot vector out, no dict on either side.

        The state vector IS the compiled state, so a caller that renders it (`printer.CanonicalPrinter`)
        or chains another epoch onto it never needs the dict -- `step` keeps the dict shape for the
        battery, which compares states field by field against the calculus's decoded ones."""
        out = self._Arr()
        self._lib.step_v6(a, c, out)
        return out

    def step(self, st, cfg_map, resets=None):
        return self.decode(self.step_raw(self.encode(st), self.control(cfg_map, resets)))
