[workspace]
authors = ["Travis Burandt <travis.burandt@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=26.5.0.dev2026072606,<27"
